### ISSUE TITLE
Please provide install package

### ISSUE THREAD

**Issue by roman-yagodin** [sachatrauwaen/openform#11]
Due to CodePlex shutdown, it's quite difficult to obtain install package for OpenForm now. 

Currently this require to download entire project archive, unpack it and search for `releases\10\<uuid-here>` files, then get smaller one and rename it to have `.zip` extension.

**Comment by robsiera** [comment]
You can find [the nightly build](https://ci.appveyor.com/project/sachatrauwaen/openform/build/artifacts) here, very stable.

**Comment by roman-yagodin** [comment]
Thanks!

**Comment by OllyHodgson** [comment]
You can now fund the latest release under https://github.com/sachatrauwaen/openform/releases

**Comment by roman-yagodin** [comment]
Thanks!
