### ISSUE TITLE
Do Not Focus on Page Load

### ISSUE THREAD

**Issue by hismightiness** [sachatrauwaen/openform#17]
I have a form that I want to have at the footer of a page, where only an e-mail address is submitted.  The page keeps scrolling to the bottom at page load, because OpenForm is automatically focusing on the form field.  How do I turn off this feature?  I don't see any settings to prevent it.

**Comment by sachatrauwaen** [comment]
You can add "focus" : "" to your options.json

https://openform.readme.io/docs/faq

**Comment by hismightiness** [comment]
Nice... I was able to get so far today on Open Content and Open Form without even thinking about documentation that I didn't even think to look there.  🤦‍♂ 

By the way... the recent updates are outstanding!  :)
