### ISSUE TITLE
Error when downloading Excel File of Submissions

### ISSUE THREAD

**Issue by jerneu-design** [sachatrauwaen/openform#25]
When downloading an Excel file a critical error occurs. 

Taken from the Admin Log

`Message:Could not load file or assembly 'EPPlus, Version=4.5.2.1, Culture=neutral, PublicKeyToken=ea159fdaa78159a1' or one of its dependencies. The system cannot find the file specified.
`

**Comment by MaiklT** [comment]
You have to either install OpenContent as well, or download the OpenContent install package, extract it and cope the file EPPlus.dll into the bin directory of your web site installation. Hope that helps...

**Comment by jerneu-design** [comment]
Thank for the tip! Copying the dll solves the error.
