### ISSUE TITLE
Update to v3.2

### ISSUE THREAD

**Issue by omarolvera** [sachatrauwaen/openform#3]
After upgrade to v3.2  from 3.0.1 i can not open the builder action and display the next message 
![image](https://cloud.githubusercontent.com/assets/9041219/24967562/2c79aee2-1f70-11e7-9359-17db54bdf498.png)

**Comment by sachatrauwaen** [comment]
For OpenForm 3.2 it is required to install OpenContent 3.2.x

**Comment by omarolvera** [comment]
The module is working now.
Thank you
