### ISSUE TITLE
Localize Submit button

### ISSUE THREAD

**Issue by FabioParigi** [sachatrauwaen/openform#5]
Hi Dear
I try to localize submit button addin in Option localized language file /Portals/0/OpenForm/Templates/Contatti/options.it-IT.json

this
```
	"buttons": {
		"submit": {
			"title": "Invia"
		}
	}
```

but nothing
Can you help me?
thanks
Fabio

**Comment by sachatrauwaen** [comment]
Hi,
Localization of submit button is in the dnn localizations resources.
