### ISSUE TITLE
Controller not found issue

### ISSUE THREAD

**Issue by Timo-Breumelhof** [sachatrauwaen/openform#6]
OC 3.5.1 & OF 3.2.0
After selecting a template I click "Template settings" and get this error:
Not Found : {"Message":"Controller not found for https://dnn7dev.local/Portalfolder/DesktopModules/OpenForm/API/OpenFormAPI/Settings?Template=/Portals/Portalfolder/OpenForm/Templates/Subscribe/schema.json.  in namespaces: Satrabel.OpenForm.Components."}

**Comment by sachatrauwaen** [comment]
I canot reproduce the issue. It sound as a local issue.

**Comment by Timo-Breumelhof** [comment]
Hi Sacha, sorry if I wasted your time, but could it be that it's because I'm on a child portal?
In my error it looks like it's not addressing the desktopmodule folder front he root, but from the base of the portalalias. My Portal Alias = dnn7dev.local/Portalfolder

**Comment by sachatrauwaen** [comment]
I checked it on a child portal . No issue.

http://localhost:54068/child/en-us/DesktopModules/OpenForm/API/OpenFormAPI/Settings?Template=/Portals/1/OpenForm/Templates/Contact/schema.json

Do you are on a multi language portal ?
Do you are on a IIS folder ?

**Comment by Timo-Breumelhof** [comment]
The local installation (DNN 7.4.2) is directly in a folder, not in a subfolder.
Portal is a child portal (there also is a root portal dnn7dev.local): https://dnn7dev.local/"mysite"
BTW, I am using https locally (but that should not be the issue I think).
And there is no core localization in place.
I also checked if there might be something wrong with the Portal home directory, but that seems to be fine too.
BTW, I did use the portal name as the portal directory name and not an id. (I always do)

**Comment by Timo-Breumelhof** [comment]
I now tried it on the Root portal and I get the same error. Weird.

**Comment by Timo-Breumelhof** [comment]
Ok, I tried a similar installation and there it does work.. Sorry about that, I'll try to find the difference..

**Comment by Timo-Breumelhof** [comment]
HTTPS  also does not cause this is seems..
