### ISSUE TITLE
Uh-oh, something broke: Internal Server Error

### ISSUE THREAD

**Issue by FabioParigi** [sachatrauwaen/openform#7]
Dear Sacha
I have this problem, DNN only one language italian, Contact page, import my standard contact for, test the form I receive this error in a javascript popup

Uh-oh, something broke: Internal Server Error
[https://image.ibb.co/kvcgCR/Capture.png](url)

I have googled find and installed this,https://ci.appveyor.com/project/sachatrauwaen/opencontent/build/02.00.00.827-hotfix/versions_date/artifacts

but nothing change, can you help me?
Thanks
Fabio

**Comment by FabioParigi** [comment]
If can be help you I think it's a juquery error, consolle error;
jquery.js?cdv=110:8526 POST http://staging25.xxxxxx.net/DesktopModules/OpenForm/API/OpenFormAPI/Submit 500 (Internal Server Error)

**Comment by sachatrauwaen** [comment]
Hi, can you look in the dnn log files and give me the full stack trace of the error

**Comment by FabioParigi** [comment]
Dear Sacha
It's the first thing I have tried to look for. But there nothing. No error in logs event
Fabio

**Comment by robsiera** [comment]
Try this: open \DotNetNuke.log4net.config and add  
`
 <logger name="OpenContent">
    <level value="Info"/>
  </logger>
` 
trigger the error again and look at your latest log in \portals\_default\logs

**Comment by FabioParigi** [comment]
No error in event viewer
This is my config file:

`<?xml version="1.0" encoding="utf-8" ?>
<log4net>
  <appender name="RollingFile" type="log4net.Appender.RollingFileAppender">
    <file value="Portals/_default/Logs/" />
    <datePattern value="yyyy.MM.dd'.log.resources'" />
    <rollingStyle value="Date" />
    <staticLogFileName value="false" />
    <appendToFile value="true" />
    <maximumFileSize value="10MB" />
    <maxSizeRollBackups value="5" />
    <lockingModel type="log4net.Appender.FileAppender+MinimalLock"/>
    <layout type="log4net.Layout.PatternLayout">
      <conversionPattern value="%date [%property{log4net:HostName}][Thread:%thread][%level] %logger - %message%newline" />
      <locationInfo value="true" />
    </layout>
  </appender>
  <root>
    <level value="ERROR" />
    <appender-ref ref="RollingFile" />
  </root>
  <logger name="OpenContent"> <level value="Info"/> </logger>
</log4net>`

**Comment by robsiera** [comment]
do not look at event viewer. Look at your latest log in folder \portals_default\logs

**Comment by FabioParigi** [comment]
ok found the problem

2018-01-22 14:35:42,597 [][Thread:10][ERROR] OpenForm - System.IO.FileLoadException: Could not load file or assembly 'System.Web.Helpers, Version=2.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'System.Web.Helpers, Version=2.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at Satrabel.OpenContent.Components.Json.JsonUtils.JsonToDynamic(String json)
   at Satrabel.OpenForm.Components.OpenFormUtils.GenerateFormData(String form, String& formData)
   at Satrabel.OpenForm.Components.OpenFormAPIController.Submit(JObject form)

**Comment by sachatrauwaen** [comment]
This typically issue after a dnn upgrade where you missing next

What you need is:
`
<dependentAssembly>
        <assemblyIdentity name="System.Web.Helpers" publicKeyToken="31bf3856ad364e35" />
        <bindingRedirect oldVersion="1.0.0.0-3.0.0.0" newVersion="3.0.0.0" />
    </dependentAssembly>
`
    



in <runtime> section of web.config

**Comment by FabioParigi** [comment]
Oh yes thanks a lot
now It work!!!!!
