### ISSUE TITLE
Install version download?

### ISSUE THREAD

**Issue by inu-web** [sachatrauwaen/openform#8]
Hi!
There is just a source code Version for Download in the releases Section.
Is there a Install version of the module somewhere?

Please can you provide a compiled Install Version like you do at the openContent Module repository?
Thanks in advance
Gerald

**Comment by robsiera** [comment]
You can find [the nightly build](https://ci.appveyor.com/project/sachatrauwaen/openform/build/artifacts) here, very stable.

**Comment by inu-web** [comment]
Thanks a lot rob!
regards
Gerald
