### ISSUE TITLE
Using the Alpaca Form Builder

### ISSUE THREAD

**Issue by inu-web** [sachatrauwaen/openform#9]
Hi
I cannot find out how to access the alpaca form builder.
The action menu on the module does not show this entry even if it is defined correctly in the modules definitions (FormBuilder | Form Builder | DesktopModules/OpenForm/AlpacaFormBuilder.ascx)

Any help to find out what I am doing wrong is highly appreciated
thanks and regards
Gerald

**Comment by robsiera** [comment]
Go to "Edit Template Files". There you will find a button to "Activate Builder".
Be careful, make a backup of your template first, as the Builder does not support every feature and will overwrite your current schema/options files.

**Comment by inu-web** [comment]
Great Support on a great module - Thanks a lot - did not realize this button even if it is the same principle as in open content - which is a great module too!
Thanks a lot for making this freely available and giving immediate support !
Appreciate your efforts very much!
Kind regards
Gerald
